// app/privacyPolicy/page.js
import React from "react";

export default function PrivacyPolicyPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-3xl">
      <h1 className="text-4xl font-extrabold text-gray-900 mb-6 text-center">
        Privacy Policy
      </h1>

      <section className="mb-8">
        <p className="text-gray-700 leading-relaxed mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="text-gray-700 leading-relaxed">
          By using the Service, You agree to the collection and use of
          information in accordance with this Privacy Policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Interpretation and Definitions
        </h2>

        <h3 className="text-2xl font-semibold text-gray-700 mb-3">
          Interpretation
        </h3>
        <p className="text-gray-700 leading-relaxed mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="text-2xl font-semibold text-gray-700 mb-3">
          Definitions
        </h3>
        <ul className="list-disc list-inside space-y-2 text-gray-700 pl-4">
          <li>
            <p>
              <strong className="font-medium text-gray-800">Account</strong>{" "}
              means a unique account created for You to access our Service or
              parts of our Service.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Company</strong>{" "}
              (referred to as either "the Company", "We", "Us" or "Our" in this
              Agreement) refers to{" "}
              <span className="font-semibold">[Your Company Name]</span>,{" "}
              <span className="font-semibold">[Your Company Address]</span>.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Cookies</strong> are
              small files that are placed on Your computer, mobile device or any
              other device by a website, containing the details of Your Browse
              history on that website among its many uses.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Country</strong>{" "}
              refers to: [Your Country, e.g., India].
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Device</strong>{" "}
              means any device that can access the Service such as a computer, a
              cellphone or a digital tablet.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">
                Personal Data
              </strong>{" "}
              is any information that relates to an identified or identifiable
              individual.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Service</strong>{" "}
              refers to the Website.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">
                Service Provider
              </strong>{" "}
              means any natural or legal person who processes the data on behalf
              of the Company. It refers to third-party companies or individuals
              employed by the Company to facilitate the Service, to provide the
              Service on behalf of the Company, to perform services related to
              the Service or to assist the Company in analyzing how the Service
              is used.
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Usage Data</strong>{" "}
              refers to data collected automatically, either generated by the
              use of the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">Website</strong>{" "}
              refers to [Your Website Name], accessible from{" "}
              <a
                href="[Your Website URL]"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                [Your Website URL]
              </a>
            </p>
          </li>
          <li>
            <p>
              <strong className="font-medium text-gray-800">You</strong> means
              the individual accessing or using the Service, or the company, or
              other legal entity on behalf of which such individual is accessing
              or using the Service, as applicable.
            </p>
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-2xl font-semibold text-gray-700 mb-3">
          Types of Data Collected
        </h3>

        <h4 className="text-xl font-medium text-gray-700 mb-2">
          Personal Data
        </h4>
        <p className="text-gray-700 leading-relaxed mb-4">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="list-disc list-inside space-y-2 text-gray-700 pl-4 mb-4">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-xl font-medium text-gray-700 mb-2">Usage Data</h4>
        <p className="text-gray-700 leading-relaxed mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="text-gray-700 leading-relaxed mb-4">
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>
        <p className="text-gray-700 leading-relaxed">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Use of Your Personal Data
        </h2>
        <p className="text-gray-700 leading-relaxed mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc list-inside space-y-2 text-gray-700 pl-4">
          <li>
            <strong className="font-medium text-gray-800">
              To provide and maintain our Service
            </strong>
            , including to monitor the usage of our Service.
          </li>
          <li>
            <strong className="font-medium text-gray-800">
              To manage Your Account:
            </strong>{" "}
            to manage Your registration as a user of the Service. The Personal
            Data You provide can give You access to different functionalities of
            the Service that are available to You as a registered user.
          </li>
          <li>
            <strong className="font-medium text-gray-800">
              For the performance of a contract:
            </strong>{" "}
            the development, compliance and undertaking of the purchase contract
            for the products, items or services You have purchased or of any
            other contract with Us through the Service.
          </li>
          <li>
            <strong className="font-medium text-gray-800">
              To contact You:
            </strong>{" "}
            To contact You by email, telephone calls, SMS, or other equivalent
            forms of electronic communication, such as a mobile application's
            push notifications regarding updates or informative communications
            related to the functionalities, products or contracted services,
            including the security updates, when necessary or reasonable for
            their implementation.
          </li>
          {/* Add more uses of data */}
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Disclosure of Your Personal Data
        </h2>

        <h3 className="text-2xl font-semibold text-gray-700 mb-3">
          With Service Providers
        </h3>
        <p className="text-gray-700 leading-relaxed mb-4">
          We may share Your personal information with Service Providers to
          monitor and analyze the use of our Service, to contact You.
        </p>

        <h3 className="text-2xl font-semibold text-gray-700 mb-3">
          For Business Transfers
        </h3>
        <p className="text-gray-700 leading-relaxed mb-4">
          We may share or transfer Your personal information in connection with,
          or during negotiations of, any merger, sale of Company assets,
          financing, or acquisition of all or a portion of Our business to
          another company.
        </p>
        {/* Add more disclosure scenarios */}
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Retention of Your Personal Data
        </h2>
        <p className="text-gray-700 leading-relaxed mb-4">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Links to Other Websites
        </h2>
        <p className="text-gray-700 leading-relaxed mb-4">
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party's site. We strongly advise You to review the Privacy
          Policy of every site You visit.
        </p>
        <p className="text-gray-700 leading-relaxed">
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Changes to this Privacy Policy
        </h2>
        <p className="text-gray-700 leading-relaxed mb-4">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="text-gray-700 leading-relaxed">
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
      </section>

      <section>
        <h2 className="text-3xl font-bold text-gray-800 mb-4">Contact Us</h2>
        <p className="text-gray-700 leading-relaxed mb-2">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul className="list-disc list-inside space-y-2 text-gray-700 pl-4">
          <li>
            By email:{" "}
            <a
              href="mailto:[Your Email]"
              className="text-blue-600 hover:underline"
            >
              [Your Email]
            </a>
          </li>
          <li>
            By visiting this page on our website:{" "}
            <a
              href="[Your Contact Page URL]"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              [Your Contact Page URL]
            </a>
          </li>
          {/* Add other contact methods */}
        </ul>
      </section>
    </div>
  );
}
